name: Build-and-Test-CLANG-Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        clang: [18]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v4
  
    - name: Install the latest Clang compiler.
      working-directory: Tests
      run:  |
            sudo apt update && sudo apt upgrade
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh 18

    - name: Configure CMake for Jsonifier
      working-directory: ./
      run: |
           sudo cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build the Test
      working-directory: ./Build
      run: |
           sudo cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Clear the Build folder
      run: |
            sudo rm -rf ./Build

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/clang++-18 -DJSONIFIER_TEST="TRUE"

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: ./Build/Tests
      run: |
           ./Json-Performance
      continue-on-error: true