name: Build-And-Test-CLANG-MacOs

on:
  push:
    branches:
    - main
    - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        clang: [15]
        build_type: [Debug, Release]
        std: [23]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: Tests
      run: cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DGITHUB_BRANCH_TYPE=${{github.ref}}

    - name: Build the Test
      working-directory: Tests/Build
      run: cmake --build . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: Tests/Build
      run: ./Json-Performance