name: Build-and-Test-CLANG-MacOS

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        clang: [17]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest xcode compiler.
      run: |
            sudo softwareupdate -i xcode
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew install rbenv
            rbenv init
            gem install xcode-install
            xcversion list
            xcversion install 12.5
            sudo xcode-select -switch /Applications/Xcode.app
            
    - name: Install Seaborn
      run: |
            pip install seaborn

    - name: Install Nasm.
      run: |
            brew install nasm

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DJSONIFIER_TEST="TRUE"

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: ./Build/Tests
      run: |
           ./Json-Performance
      continue-on-error: true
      