name: Build-and-Test-GCC-Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        gcc: [12]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v4
  
    - name: Install the latest gcc compiler.
      working-directory: Tests
      run:  |
            sudo apt-get install build-essential
            sudo apt-get install g++-12

    - name: Configure CMake for Jsonifier
      working-directory: ./
      run: |
           sudo cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DJSONIFIER_LIBRARY="true"

    - name: Build the Test
      working-directory: ./Build
      run: |
           sudo cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Clear the Build folder
      run: |
            sudo rm -rf ./Build

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/usr/bin/g++-12 -DJSONIFIER_TEST="true" -DJSONIFIER_LIBRARY="true"

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: ./Build/Tests
      run: |
           ./Json-Performance
      continue-on-error: true